disableKinds = ["taxonomy", "taxonomyTerm"]

publishDir = "docs"
RelativeURLs=true

# Page settings
baseURL = "/"
languageCode = "en"
title = "Emircan ERKUL | Personal Website"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-84655550-4"


[params]
    author = "Emircan ERKUL"
    description = "I spend my time and energy on personal and technical development. Each day I want to be at least one step ahead."

    primaryColor = "#4c74b8"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Emircan ERKUL"
        tagline = "Full Stack Web Developer focused on <span>Drupal</span>"
        avatar = "avatar.png"

    [params.contact]
        enable = true
        location = "Turkey & Remote"

        [[params.contact.list]]
        icon = "icon-github"
        url = "//github.com/emircanerkul"
        text = "Github"
        [[params.contact.list]]
        icon = "icon-linkedin"
        url = "//www.linkedin.com/in/emircanerkul"
        text = "Linkedin"

    [params.skills]
        enable = true

        [[params.skills.list]]
        [[params.skills.list.items]]
        details = "Php, Symfony, Drupal API"
        [[params.skills.list.items]]
        details = "Soap, Rest, GraphQL"
        [[params.skills.list.items]]
        details = "MySQL, NoSQL"
        [[params.skills.list.items]]
        details = "Html, Css, Sass, JS, jQuery"
        [[params.skills.list.items]]
        details = "Yaml, Json, Xml, Csv, Env"


    [params.tools]
        enable = true

        [[params.tools.list]]
        [[params.tools.list.items]]
        details = "VSCode, Xdebug, Composer, npm"
        [[params.tools.list.items]]
        details = "Docker, Docksal, Drush, Devel"
        [[params.tools.list.items]]
        details = "WSL2, Windows, Mac, Linux"
        [[params.tools.list.items]]
        details = "Git, Gitlens, Gitpod, GitHub, GitLab"
        [[params.tools.list.items]]
        details = "MailHog, phpMyAdmin, MySQL Workbench, WinSCP"
        [[params.tools.list.items]]
        details = "Sketch, Figma, Photoshop"

    [params.certificates]
        enable = true

        [[params.certificates.list]]
        title = "Certified Drupal 9 Developer"
        issuer = "Acquia"
        dates = "Nov 2022"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Lifelong learning"
        university = "Mostly Online Platforms"
        dates = "2014 - ∞"
        [[params.education.list]]
        degree = "BA in Computer Science"
        university = "Kocaeli University"
        dates = "2017 - 2022"

    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Turkish"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Spirituality"
        [[params.interests.list]]
        name = "3D Modelling"
        [[params.interests.list]]
        name = "Playing Instruments"
        [[params.interests.list]]
        name = "Learning Useful Things"

    [params.summary]
        enable = true
        text = "I spend my time and energy on personal and technical development. Each day I want to be at least one step ahead."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Drupal Developer"
        dates = "March 2022 - Now"
        company = "EPAM"
        details = "Working with great EPAMers on global projects, especially in the pharma industry."

        [[params.experience.list]]
        title = "Drupal Developer"
        dates = "Sep 2020 - Feb 2022"
        company = "Drupart"
        details = "My first full-time professional life just began in the middle of university studying. I met great people that light my way. \n\nThe colors of this light are;"
        [[params.experience.list.items]]
        details = "Working as a Team and using collaboration tools like Git"
        [[params.experience.list.items]]
        details = "Multitasking thanks to working on multiple great projects at the same time"
        [[params.experience.list.items]]
        details = "Being Agile with great time management"
        [[params.experience.list.items]]
        details = "Developing with fewer Code Smells and high standard"
        [[params.experience.list.items]]
        details = "OOP, Modular Design, and Atomic Design"
        [[params.experience.list.items]]
        details = "Drupal Module and Theme development"
        [[params.experience.list.items]]
        details = "Drupal 7 to Drupal 9 migrations"
        [[params.experience.list.items]]
        details = "And more technical and personal benefits…"

        [[params.experience.list]]
        title = "Freelance Developer"
        dates = "Jan 2019 - Sep 2020"
        company = "Freelancer"
        details = "My professional life began as a freelance developer due to university and life limits. As a freelancer, I learn lots of things like time management, client relationships, and more. \n\nFirstly I had to select my clients in Turkish speakers. After I become to speak and understand English, I moved my freelancer level to higher and was able to reach all English-spoken people."
        [[params.experience.list.items]]
        details = "Drupal 9 Website Development and System Design for pdfseva.com"
        [[params.experience.list.items]]
        details = "Full-stack Web Development and System Design for ringtonehd.com"
        [[params.experience.list.items]]
        details = "Full Stack Web Developer at Tvoystol for one month"
        [[params.experience.list.items]]
        details = "Full Stack Web Developer at Modalobby for two month"
        [[params.experience.list.items]]
        details = "Product synchronization via Prestashop API for otolastikci.com.tr"
        [[params.experience.list.items]]
        details = "Rest API Development for kurtuluskuruyemis.com.tr"
        [[params.experience.list.items]]
        details = "And much more..."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Data Visualization"
        meta = "Open Source"
        tagline = "This project is about spreadsheet visualization is totally on the client-side. In this project, I used SheetJS and WebSQL. There is an online demo on my GitHub page."

        [[params.projects.list]]
        title = "Augmented Reality"
        meta = "Open Source"
        tagline = "I demonstrated how AR works on a browser in this project that was developed and present on First Class of University. The model will be standing on a specific card. Other 6 different cards were used for giving a command to the animated model through the camera. I used jsartoolkit5 and an animated model with threejs. There is an online demo on my GitHub page."

        [[params.projects.list]]
        title = "Quotes"
        meta = "Open Source"
        tagline = "Lots of courses completed and developed an Ionic app with Firebase, Angular, and RxJS. I saw the beauty of Reactive programming on this project."

        [[params.projects.list]]
        title = "CVGen | Customizable CV Generator"
        meta = "Open Source"
        tagline = "In this project, I develop a multi-profile and multilanguage featured resume generator with a custom template engine and  Wkhtmltopdf. For the development environment, I used docker and create a docker file for this project's needs."

        [[params.projects.list]]
        title = "QGen | SQL Query Generator"
        meta = "Open Source"
        tagline = "In lots of classes like math, chemistry, linear algebra, and database design some exam questions have patterns. In this project, I demonstrate how to generate unique exams for educational institutions. Generating pdf and archive will be on the client browser. Besides generating exams, I developed hardness level calculation of questions basis on Bezier Easing. There is an online demo on my GitHub page."

        [[params.projects.list]]
        title = "Educational Projects"
        meta = "Open Source"
        tagline = "I learn through practical training and I call that learning on the road. I also share my learning processes on Github. I was thinking that repos will help other learners."

        [[params.projects.list.items]]
        details = "Weather API via API Platform: On this project, Symfony's data fixtures, doctrine migrations, data persisters, custom commands developed, and entities generated with maker bundle and customized for API platform integration. For JWT authentication admin user is an in-memory user, and other users are entities."

        [[params.projects.list.items]]
        details = "Drupal First Step: Learning Drupal Theme & Module Development and Flutter with Drupart Internship"

        [[params.projects.list.items]]
        details = "Symfony First Step: In this project, I am developing a content management system just for learning the Symfony framework."

        [[params.projects.list.items]]
        details = "RPG Game Development Adventure: In this project, I enjoyed developing a little game with fully object-oriented javascript. I share each day's progress with animated gifs. I wasn't spening all day, just I wanted to be consistent in daily development."

        [[params.projects.list.items]]
        details = "PSD to Html: I wanted to learn how to PSD to HTML and improve my front-end skills. I aimed to use different technologies at every stage of this project for my education."

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"

    [params.social]
        enable = false

        [[params.social.list]]
        icon = "icon-github"
        url = "//github.com/emircanerkul"
        title = "github"
        [[params.social.list]]
        icon = "icon-linkedin"
        url = "//linkedin.com/in/emircanerkul"
        title = "linkedin"
